build:
    dependencies:
        before:
            - pip install --target $PWD/_packages --install-option="--install-scripts=$PWD/_bin" https://github.com/FragLegs/pip/archive/patch-for-issue-2953.zip
            - pip install --target $PWD/_packages --install-option="--install-scripts=$PWD/_bin" wheel setuptools
            - PATH="$PWD/_bin:$PATH" PYTHONPATH="$PWD/_packages:$PYTHONPATH" python _packages/pip/__main__.py install --requirement Trakttv.bundle/Contents/Tests/requirements.txt
    environment:
        python: 2.7.7
    tests:
        override:
            -
                command: export PATH="$PWD/_bin:/home/scrutinizer/.pyenv/versions/2.7.7/bin:$PATH"; export PYTHONPATH="$PWD/_packages:$PYTHONPATH"; ./Tools/run_tests.sh
                coverage:
                    file: .coverage
                    format: py-cc
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths:
        - Trakttv.bundle/Contents/Code/*
        - Trakttv.bundle/Contents/Libraries/Shared/plugin/*